### ISSUE TITLE
shadow on unfocus clients

### ISSUE THREAD

**Issue by paranoid73** [meriadec/awesome-sombra#1]
Hi , 
Nice desktop config but when i use it ,  i notice there is a shadow on unfocus windows for all apps .
thank you in advance for your answer

**Comment by meriadec** [comment]
not sure I get it. shadow is not handled by awesome but by your composite manager. can you provide more details on how to reproduce & screenshot?

**Comment by paranoid73** [comment]
Resolved , it was GTK , i have created a file to fix it.
According to https://wiki.archlinux.org/index.php/GTK%2B

Thank you

**Comment by meriadec** [comment]
Nice!
