### ISSUE TITLE
bug after maximizing a window

### ISSUE THREAD

**Issue by paranoid73** [meriadec/awesome-sombra#2]
HI , 
impressively configuring but the only bug comes after maximizing a window , we notice that the window is not the same size , possible to fix it ?
![2018 09 12-06 57 12 screenshot](https://user-images.githubusercontent.com/34898251/45407536-3574ed00-b659-11e8-96d2-4dc69e0a4871.png)

**Comment by meriadec** [comment]
Hey! Yes, I've fixed the problem but I now maintain it directly [in my dotfiles repo](https://github.com/meriadec/dotfiles/tree/master/config/awesome). I may consider using git submodule to keep atomicity :/

I would recommend to use the updated version, and after you can play with those values:

- enable "smart borders" [here](https://github.com/meriadec/dotfiles/blob/5c9a7dfe5f80e19dba3361aadddafc32c5b3d99f/config/awesome/rc.lua#L12)
- tweak the smart borders style [here](https://github.com/meriadec/dotfiles/blob/master/config/awesome/modules/smart-borders.lua#L10-L16)

The bug should be fixed, for maximizing/un-maximizing, and fullscreen/un-fullscreen

if you have any question don't hesitate!
I will put in my todo list to update this repo soon

**Comment by paranoid73** [comment]
yes, but the last update of smart borders does not have the same appearance so , maybe I can just correct this bug

**Comment by meriadec** [comment]
You can make it looks the same (and more!) by changing those values

```
local GUTTER = 10
local WEIGHT = 1
local STRING_OFFSET = 2
local ARROW_WEIGHT = 5
local ARROW_WIDTH = 50
local SMART_GAP = 0
local COLOR = gears.color("#2b303b")
```

**Comment by paranoid73** [comment]
a correction was before my eyes and I ignored, thanks and really impressionnate config

**Comment by meriadec** [comment]
:)
